<!-- Custom Shipping Policy Product Tab - Pulls Data From CMS -->
<!--< ?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_policy')->toHtml(); ?>-->
<div style="text-align:left;">
    <b>Royal Mail Tracked 24 Hour</b>
    <p>Royal Mail Tracked 24 has an estimated delivery time of between 1-2 working
        days and only applies to orders placed before 3.00pm Monday-Friday
        (excluding public holidays) Orders placed after this time will be despatched
        on the next working day. Customers living in remote locations may experience
        slightly longer delivery times.
    <p>Orders placed on the Friday will still be delivered Saturday
    </p>
    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.
    </p>

    <b>Royal Mail Tracked 48 Hour</b>
    <p>Royal Mail Tracked 48 has an estimated delivery time of between 2-3 working
        days and only applies to orders placed before 3.00pm Monday-Friday
        (excluding public holidays) Orders placed after this time will be despatched
        on the next working day. Customers living in remote locations may experience
        slightly longer delivery times. </p>
    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.</p>


    <b>Royal Mail First Class Postage – Free</b>
    <p>Royal Mail First Class post no signature required is an economy postal
        service with an estimated delivery time of between 1-3 working days and only
        applies to orders placed before 3.00pm Monday-Friday (excluding public
        holidays) Orders placed after this time will be despatched on the next
        working day. Customers living in remote locations may experience slightly
        longer delivery times.
    </p>
    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.
    </p>

    <b>DPD - International</b>
    <p>Estimated Delivery to your destination is between 2-3 working days. This is a
        tracked service. </p>

    <b>DPD Saturday Delivery</b>
    <p>Saturday delivery only applies to orders placed before 6:30pm on Friday. This
        is a fully tracked service.</p>
    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.</p>
    <p>Please note this delivery option is not available
        for customers in Guernsey,
        Jersey, Northern Ireland, Scottish highlands or Aberdeenshire.</p>

    <b>Free Shipping over £20</b>
    <p>Orders over £20 will receive free Royal Mail tracked delivery service and
        will
        require a signature. Please allow 2 to 3 working days for delivery after
        dispatch.
    </p>

    <b>First Class Postage – Free</b>
    <p>Free delivery without tracking (no signature required) is only available on
        10ml
        e-liquid orders placed with a maximum of 12 bottles per order with
        Royal Mail’s first class delivery service. Please allow 1 to 3
        working days for delivery after dispatch.
    </p>

    <b>DPD Next Working Day</b>
    <p>Next day delivery only applies to orders placed before 6:30pm Monday-Friday,
        orders placed after this time will be despatched the next working day.
        This is a fully tracked service. Orders placed on a Friday will not be
        delivered on a Saturday using this service.</p>
    <p>Please note that bank holidays will affect this service. Please get in
        contact for more information.</p>
    <p>Please note this delivery option is not available
        for customers in Guernsey,
        Jersey, Northern Ireland, Scottish highlands or Aberdeenshire.</p></div>um dolor sit amet, consectetur adipisicing elit. At autem beatae dolore, eaque enim eveniet excepturi fugiat maiores molestiae neque placeat quo sequi sit temporibus unde vero voluptate! Est, officiis.</p>