<!-- < ?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_info')->toHtml(); ?> -->


<h2>Custom Shipping Information</h2>
<!--<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad debitis et magnam obcaecati porro quae repellendus ullam vitae voluptas voluptatem! Autem earum enim fugiat incidunt libero maxime obcaecati quam veritatis!</p>-->

<?php

//$order = $block->getOrderItems();
//$orderItems = $order->getAllItems();
//$code = $orderItems->getShippingMethod();
//
//echo 'order' . $code;

//$order->getShippingMethod();


?>